### ISSUE TITLE
How to add both has_one_attached and has_many_attached into one file?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [madeindjs/active_storage-send_zip#24]
Is it possible to grab both has_one_attached active storage files and has_many_attached active storage files in one single zip?

`format.zip {send_zip @post.photos + @post.one_document} 
`

**Comment by madeindjs** [comment]
Is this works ?

~~~ruby

documents = @post.photos
documents << @post.one_document
format.zip { send_zip documents}
~~~

**Comment by RailsCod3rFuture** [comment]
I will try again tomorrow. If you get the opportunity, please let me know.

Thank you.

**Comment by RailsCod3rFuture** [comment]
Its working with arrays, but not has_one_attachments.

**Comment by RailsCod3rFuture** [comment]
```
ActiveRecord::AssociationTypeMismatch in controller#zip_files 

ActiveStorage::Attachment(#544444444) expected, got # <ActiveStorage::Attached::One >> which is an instance of ActiveStorage::Attached::One
```

**Comment by RailsCod3rFuture** [comment]
Is it possible if you can patch this functionality in?

**Comment by madeindjs** [comment]
I don't understand you problem. I think all of theses case works

- with `ActiveStorage::Attached::Many`

~~~ruby
send_zip @post.photos + @post.one_document
~~~

- with `ActiveStorage::Attached::One` +  `ActiveStorage::Attached::Many`

~~~ruby
documents = @post.photos
documents << @post.one_document
send_zip documents
~~~

- with `ActiveStorage::Attached::One`

~~~ruby
send_zip [@post.one_document]
~~~

Could you confirm me is this correct ?
