### ISSUE TITLE
custom zip name

### ISSUE THREAD

**Issue by Frzurita** [madeindjs/active_storage-send_zip#30]
Hi! is there a way to provide a custom .zip name?
I'm using this controller as an example:
```
    def download_documents
      send_zip document_files
    end
```
which is bounded to a GET route `documents/download_documents` but the .zip file has the name my.zip.

is there a way to change the name?

**Comment by djarkobobanov** [comment]
you can find the options in the source code, just use:
`send_zip document_files, filename: 'xxx.zip'`
