### ISSUE TITLE
Zip containing undefined number of subfolders and files

### ISSUE THREAD

**Issue by sethaddison** [madeindjs/active_storage-send_zip#32]
I have 2 models: Listings and Offers. A listing has_many offers. and offers belong_to a listing. A listing can have an undefined number of offers. An offer can have an undefined number of documents (ActiveStorage).

I am trying to allow a user to download a zip file for each listing that contains subfolders for each of the offers, with each offer subfolder containing the documents for that particular offer. Is this possible?

**Comment by madeindjs** [comment]
Yes of course. I think you should use [with `Hash`](https://github.com/madeindjs/active_storage-send_zip#with-hash) feature. Here a quick implementation:

```rb
zip_options = {}

Listing.includes(:offers).all.each do |listing|
  documents_by_offer = {}
  listing.offers.each do |offer|
    documents_by_offer[offer.name] = offer.documents
  end
  
  zip_options[listing.name] = documents_by_offer
end

send_zip zip_options
```
Let me know if it works ;)

**Comment by sethaddison** [comment]
Super cool. I reconfigured my code a bit, but once I saw your example, it made total sense. Works perfectly. Thanks!
