### ISSUE TITLE
ActionController::UnknownFormat

### ISSUE THREAD

**Issue by mayordwells** [madeindjs/active_storage-send_zip#4]
I am running a Rails v6.0.0.rc1
I have added this to mime_types.rb in initializers folder
`Mime::Type.register "application/zip", :zip`

And I have this in my controller 
```
def show
   @welder_certificate_documentation = WelderCertificateDocumentation.find(params[:id])
    respond_to do |format|
      format.zip  { send_zip @welder_certificate_documentation.ndt_reports }
    end
end
```

But when I try to download in my view I'm getting this error 

<img width="1278" alt="Screen Shot 2019-05-08 at 5 00 39 PM" src="https://user-images.githubusercontent.com/1370340/57381318-5aebd380-71b3-11e9-8214-a0afe4b24d36.png">

Any idea how to fix this?

**Comment by madeindjs** [comment]
As stacktrace says, error come from *your* mime declaration. I think it's because you re-declare `zip` mime type but [Rails already set it](https://github.com/rails/rails/blob/v6.0.0.rc1/actionpack/lib/action_dispatch/http/mime_types.rb#L49). Hope it help you

**Comment by mayordwells** [comment]
Hi @madeindjs thanks for your prompt response, the main problem is, even when I didn't have the mime type declared, it was returning the same error. 
I decided to set this mime type thinking it will make the error go away. 

I have removed the declaration for the mime_types file and restarted my server and tried to download the file again, but I got the same error.

**Comment by mayordwells** [comment]
I fixed it by explicitly setting the format to zip in routes and the view file. 

This is important but was not mentioned in the documentation. This took me a few hours to figure out. I hope this helps someone. 

In Routes (use lambda constraint if you only want the format to be zip and nothing else, else use the simple constraint, both worked for me). Ref: https://guides.rubyonrails.org/routing.html#request-based-constraints

<img width="872" alt="Screen Shot 2019-05-08 at 7 26 56 PM" src="https://user-images.githubusercontent.com/1370340/57391667-a7d9a500-71c7-11e9-91cb-0f2b0dd064f6.png">

Controller:
```
def download
      @welder_certificate_documentation = WelderCertificateDocumentation.find(params[:id])
      respond_to do |format|
        format.zip  { send_zip @welder_certificate_documentation.ndt_reports }
      end
end
```

View:
<img width="941" alt="Screen Shot 2019-05-08 at 7 26 17 PM" src="https://user-images.githubusercontent.com/1370340/57391862-043cc480-71c8-11e9-83f1-fbdb30dba583.png">

**Comment by madeindjs** [comment]
This is really strange because I havn't this problem with my Rails application who also use 6.0.0.rc1 . But your problem does not seem be related to active_storage-send_zip gem. Maybe it's because you define a zip format only route but in my example I use both HTML and zip ?

**Comment by mayordwells** [comment]
I was actually trying to do this in the show action before. As you can see in my original question. 
Maybe it is not connected to the Gem, but the error occurred at the respond_to block. 

Not sure if its because I defined a zip only format. 

For this particular feature, I did not need an HTML template to render. 

Any Idea how to specify a custom, dynamic name for my zip file? @madeindjs if this feature doesn't exist I'd be happy to help with it.

**Comment by madeindjs** [comment]
Did you try to change the default format for you route? https://guides.rubyonrails.org/routing.html#defining-defaults

**Comment by mayordwells** [comment]
No, I did not change the default format. @madeindjs

**Comment by mayordwells** [comment]
@madeindjs I found a way to generate special filenames for zipped file, which will overwrite the default specified here.

https://github.com/madeindjs/active_storage-send_zip/blob/65921be2a3273aa0a2f84d5aa7780c2086ae05b9/lib/active_storage/send_zip.rb#L17

Here's how I did it. In my situation, I wanted to concatenate all file names and separate them by a "+" sign and then remove all white spaces in between the names. 

```
def generate_filename_for(welder_certificate_documentation)
    filenames = []
    welder_certificate_documentation.ndt_reports.each do |ndt_report|
       filenames << ndt_report.blob.filename.to_s
    end
    concat_filenames(filenames)
end

def concat_filenames(filenames)
   (filenames * "+").tr('.pdf', '').delete(' ')
end
```

and then I used it like this:

```
def download
      @welder_certificate_documentation = WelderCertificateDocumentation.find(params[:id])
      filename = generate_filename_for @welder_certificate_documentation
      respond_to do |format|
        format.zip  { send_zip @welder_certificate_documentation.ndt_reports, filename: "#{filename}.zip" }
    end
end
```
